name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  prepare:
    uses: ./.github/workflows/_job-release-prepare.yml

  cargo-test:
    uses: ./.github/workflows/_job-cargo-test.yml

  integration-test:
    uses: ./.github/workflows/_job-integration-test.yml

  docker-build:
    needs: [prepare, cargo-test, integration-test]
    uses: ./.github/workflows/_job-docker-build.yml
    with:
      image_tags: >-
        ghcr.io/${{ github.repository_owner }}/kalatori:${{ needs.prepare.outputs.version }},
        ghcr.io/${{ github.repository_owner }}/kalatori:latest
      push: true
    permissions:
      contents: read
      packages: write

  github-release:
    needs: [prepare, docker-build]
    uses: ./.github/workflows/_job-github-release.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      changelog_body: ${{ needs.prepare.outputs.changelog_body }}
    permissions:
      contents: write

  docs-deploy:
    needs: [prepare]
    uses: ./.github/workflows/_job-docs-deploy.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      alias: latest
      set_default: true
    permissions:
      contents: write
