name: Rust clippy

on:
  pull_request:
  push:
    branches:
      - main
      - stable

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  linter:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install subxt-cli
        run: make install-subxt-cli
      - name: Download chain metadata
        run: make download-node-metadata-ci
      - name: Download front-end (required for daemon compilation)
        run: make download-front-end
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features
