name: Rustfmt

on:
  pull_request:
  push:
    branches:
      - main
      - stable

jobs:
  rustfmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Temporarily modify the rust toolchain version
        run: rustup override set nightly
      - name: Install rustfmt for nightly toolchain
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check
